### ISSUE TITLE
Impossible to set “quality” for cameraRef.recordAsync method

### ISSUE THREAD

**Issue by rzasinets** [expo/expo-react-native-adapter#1]
**recordAsync** method have quality parameter. Likely if we can set it to minimal value resulting video must be smaller compared to default one (size is crucial, as we need to save fragments to the server, but sending about 500Mb for 1 minute of video has no sense). But when I try to set quality by either **Camera.Constants.VideoQuality[‘720p’]** or **2** - warning appears and record is not starting. Am I doing anything wrong?

https://imgur.com/dS7wdmH

Here is a Stack: https://snack.expo.io/@defor/cameraqualityissue

It is in working state now.
If you uncomment line #210 quality: Camera.Constants.VideoQuality['480p'] - video will not be captured at all. Since warnings are disabled in “stack” mode (as I understand environment is set to production) - warning mentioned in my original post is not shown, but it is there

**Comment by sjchmiela** [comment]
Hey, @Defor! Sorry for taking this long to respond. This issue should have been fixed in https://github.com/expo/expo/commit/e2e4de4363c3d4007f4fd2232eb67626b21aa2bf. The fix will be a part of SDK 31 release. 🙂
