### ISSUE TITLE
Short videos are not captured

### ISSUE THREAD

**Issue by rzasinets** [expo/expo-react-native-adapter#2]
Snack for reference https://snack.expo.io/@defor/cameraqualityissue

If you comment lines from #217 to #220

```
if (captureFinished - captureStarted < 2500) {
      console.warn('Video is too short. Nothing is captured')
      return;
    }
```
And then tap on capture button and release it faster then 2.5 seconds - nothing will be captured. Under preview we will see just a black screen (but there should be 2.5 seconds of video). I believe it is related to some kind of delay between call recordAsync and actual recording.
Is there any workaround on this issue?

**Comment by bbarthec** [comment]
@Defor I'm closing this issue as there's answer for it [here on forums.expo.io](https://forums.expo.io/t/impossible-to-set-quality-for-cameraref-recordasync-method/13199/6?u=barthec)
